import tkinter as tk

root = tk.Tk()
root.title("Grade Analysis")

root.geometry("1000x1000")
year = tk.Text(root, height=2, width=30)
year.pack()
year.insert(tk.END, "Please Enter Yearn")
year_enter = tk.Entry(root)
year_enter.pack()
y = year_enter.get()
depart = tk.Text(root, height=2, width=30)
depart.pack()
depart.insert(tk.END, "Please enter department")
depart_enter = tk.Entry(root)
depart_enter.pack()
d = depart_enter.get()

crn = tk.Text(root, height=2, width=30)
crn.pack()
crn.insert(tk.END, "Please enter CRN")
crn_enter = tk.Entry(root)
crn_enter.pack()
crn_enter.get()
tk.mainloop()